name: Docker Scan using docker-bench
on:
  push:
  workflow_dispatch:
  
jobs:
  Container-security:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install pip 
      run: |
        curl -s https://bootstrap.pypa.io/get-pip.py | python3
    
    - name: Install the latest version docker 
      run: |
        curl -s https://get.docker.com/ | sh
        #sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
        sudo chmod g+rwx "$HOME/.docker" -R
        
    
    - name: Run docker service 
      run: |
        sudo systemctl start docker 
    - name: Install docker compose 
      run: |
        sudo pip install docker-compose
    
        
    - name: Build and deploy 
      run: |
        sudo docker pull imiell/bad-dockerfile
        sudo docker build -t imiell/bad-dockerfile ./

        
    - name: Run docker-bench-security 
      run: |
        sudo git clone https://github.com/docker/docker-bench-security.git
        cd docker-bench-security
        sudo sh docker-bench-security.sh        
        
