name: Docker Scan using docker-bench
on:
  push:
  workflow_dispatch:
  
jobs:
  Container-security:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install pip 
      run: |
         docker pull imiell/bad-dockerfile
         docker build -t imiell/bad-dockerfile/ ./
    

        
    - name: Run docker-bench-security 
      run: |
        sudo git clone https://github.com/docker/docker-bench-security.git
        cd docker-bench-security
        sudo sh docker-bench-security.sh        
        
