name: Docker Scan using docker-bench
on:
  push:
  workflow_dispatch:
  
jobs:
  Docker-security:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Use Vulnerable image 
      run: |
         docker pull imiell/bad-dockerfile
         docker images
         docker run abd4f451ddb7
         #docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
         
     
         
        
    - name: Run docker-bench-security 
      run: |
        docker run --rm --net host --pid host --userns host --cap-add audit_control \
        -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
        -v /etc:/etc:ro \
        -v /usr/bin/containerd:/usr/bin/containerd:ro \
        -v /usr/bin/runc:/usr/bin/runc:ro \
        -v /usr/lib/systemd:/usr/lib/systemd:ro \
        -v /var/lib:/var/lib:ro \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        --label docker_bench_security \
        docker/docker-bench-security
